### ISSUE TITLE
Julia interface improvements

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#11]
Here's a list of Julia interface items I'd like to tackle one day.

* adopt more idiomatic package name spelling, BridgeStan instead of Bridgestan
* export K means nothing since K is never defined
* its common Julia practice to use f! when there's an out argument; add log_density, log_density_gradient (no exclamation points) which assign to new memory (instead of using an out argument)
* can drop the ::Vector{Float64} in most use cases of zeros(D); Float64 by default
* not all defined functions are exported
* double check tests for completeness

**Comment by WardBrian** [comment]
I definitely copied the export list without doing anything to it, my bad!

Re:out parameters, I believe the functions are currently implemented as you describe (new memory each time) so we should add the ! versions

for tests we should probably just recreate the Python tests in all 3 languages eventually, those are the most complete

**Comment by roualdes** [comment]
No blame here.

Yep, I see that now.  You're right. We should the ! versions.

Agreed on the tests.

**Comment by WardBrian** [comment]
Would you like me to take a crack at some of these, or would you prefer to do it?

**Comment by roualdes** [comment]
Yes, please do.  I phrased to to do list in the first person so as not to tell anybody what to do.  I'd appreciate you giving it a go.  Thanks.

**Comment by roualdes** [comment]
@WardBrian, what do you think about adding 

```
export BS
const BS = BridgeStan
```
to the BridgeStan module and dropping all other exports?  The effect would be 

```
using BridgeStan
```

then enables `BS.log_density()` and `BS.log_density_gradient()`, ... .

This is what they do in [AbstractDifferentiation.jl](https://github.com/JuliaDiff/AbstractDifferentiation.jl/blob/master/src/AbstractDifferentiation.jl).

It's like a Julia version of Python's `import bridgestan as bs`.

To me the pithiness is nice, but I could see it also being not obvious.

**Comment by roualdes** [comment]
That's fair.  It is probably better just to remind users that `const BS = BridgeStan` is possible, in say the example.jl, rather than force it on them.
