### ISSUE TITLE
Runtime errors during `param_unconstrain` because of precision issues

### ISSUE THREAD

**Issue by mjhajharia** [roualdes/bridgestan#127]
I was re running some scripts dealing with simplexes, and ran into this.

Basically, for a valid simplex constraint, if I try to use the sampled draws from a stan program in `model.param_unconstrain`, I end up with 

```
RuntimeError: param_unconstrain() failed with exception: Exception: stan::math::simplex_free:  
Simplex variable is not a valid simplex. sum(Simplex variable) = 0.99999959, but should be 1 
```

which is of course not a bridgestan issue, and other stan interfaces have also had similar problems I think, anyway this is only because of `sig_figs` being 6 by default. I'd wager this to be a common issue as bridgestan grows. As for a fix, I don't know if that's easy to do, or even in scope for BridgeStan, but if there'd be a way of adding tolerance for the constraint checks that would be quite nice. For example I have 400 chains with 1000 draws each for 1000 dimensions, so in this case I'd avoid more significant digits solely for the sake of convenience. 

Anyway, this is not a bug, but if it's at all helpful for future scope, or if there's an easier fix other than changing `sig_figs` in `Cmdstan` itself I'd be very happy to hear about that.

I noticed this is in CmdStanR future [milestone list](https://github.com/stan-dev/cmdstanr/milestone/3) but it sort of bleeds through all Stan Interfaces.

**Comment by WardBrian** [comment]
The tolerance is a hard coded value here: https://github.com/stan-dev/math/blob/46f3c59e63851451ed1bf9b64c8f57c89fa49e8e/stan/math/prim/err/constraint_tolerance.hpp#L12

It would be nice if this was at least a `#define` so we could override it easily at compile time.

**Comment by mjhajharia** [comment]
okay makes sense, yeah that's unfortunate, for high dimensional simplexes this would definitely keep creating problems.

**Comment by WardBrian** [comment]
I think using more sig_figs in CmdStan (or CmdStan offering a binary format which has full double precision) are probably the best “solutions” for now, but it might be worth opening an issue in Stan-Dev/math about making that constant something configurable

**Comment by roualdes** [comment]
From what I see, there is not a flag for disabling this. @WardBrian would you mind filing an issue in Stan Math?

**Comment by WardBrian** [comment]
I think the issue @mjhajharia opened for a configurable tolerance is better than a flag, since one could just set it to a very high tolerance and effectively disable it that way

**Comment by WardBrian** [comment]
The next version of Stan will let this be configured at compile time
