### ISSUE TITLE
feature request: `theta_unc` taking multi dimensional arrays as input.

### ISSUE THREAD

**Issue by mjhajharia** [roualdes/bridgestan#129]
Plausibly many users would want to evaluate gradients or hessians at more than one point. At that point being able to give a multidimensional array as `theta_unc` might be very useful. internally the iteration would happen irregardless so I'm not sure if it helps a lot computationally, but definitely very convenient. As in `theta_unc` being (N,D) where D is the number of unconstrained parameters. For example if I want to evaluate hessians for all the 1000 draws from one chain of a run, I would do something like this now

```
for idx, row in enumerate(idata):
        theta = model.param_unconstrain(row)
        model.log_density_hessian(theta, out_grad=grad[idx], out_hess=hessian[idx])
```

Instead if `theta_unc` could be a multidimensional array itself I could essential provide the entire sample data for all the unconstrained parameters and then get a 3-dimensional array containing the hessians. Similarly I could get a nice matrix of the unconstrained parameters without a for loop as well, if `theta` also supported the same structure.

**Comment by roualdes** [comment]
I could imagine a convenience factor here, as you suggest.  And a serial loop in C/C++ should be faster than a loop in Python/R.

Some other thoughts:

* By the time a one-dimensional `theta_unc` reaches C/C++/Eigen (within Stan Math), it needs occupy contiguous memory.  So we'd need to deal with Numpy being row major and R/Julia/Eigen being column major, if we wanted to support a two dimensional `theta_unc`.
* Julia can easily run such a loop simultaneously in multiple threads, so the net benefit of calling a serial loop is less significant here.  
* Could we implement a loop around a two dimensional `theta_unc` using multiple threads in C++?  What are the software requirements for this?

**Comment by sethaxen** [comment]
> Julia can easily run such a loop simultaneously in multiple threads, so the net benefit of calling a serial loop is less significant here.

Would this require the model to have been compiled with `STAN_THREADS=true`?

**Comment by roualdes** [comment]
Yes.  And good point, I've been maintaining in my head `STAN_THREADS=true` as the default, but have not explicitly said this.  Any potential multi-threaded loop in C++ would require `STAN_THREADS=true` as well.  And I'm not convinced we want to enforce `STAN_THREADS=true` by default on our clients, as it can make serial log density gradient calls slower.

**Comment by roualdes** [comment]
Any objections to closing this, based on the argument above (small marginal benefit relative to the complexity required to handle this in the C interface)?

**Comment by WardBrian** [comment]
No objections here
