### ISSUE TITLE
Add to Getting Started doc necessary dependencies on Stan and Stan Math

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#136]
From our review for the Journal of Open Source Software, https://github.com/openjournals/joss-reviews/issues/5236, it was recommended that we address more clearly our software dependencies on Stan and Stan Math, including mentioning these as included git submodules.

**Comment by bob-carpenter** [comment]
Seems obvious to us, but definitely worth mentioning.  We can just add a section on dependencies and include NumPy.  Is there anything else?

**Comment by WardBrian** [comment]
The individual documentation pages for each language interface mention their dependencies, so I think we're good there.
