### ISSUE TITLE
Add to Getting Started doc recommendation to use --shallow-submodules 

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#137]
From our review for the Journal of Open Source Software, https://github.com/openjournals/joss-reviews/issues/5236, it was recommended that we suggest to users to clone the BridgeStan repository with `--shallow-submodules` since we don't necessarily need the git histories associated with Stan and Stan Math and this will save much disk space.

On my machine cloning BridgeStan using `--shallow-submodules` reports 

```
$ du -hs bridgestan 
698M	bridgestan
```

and without `--shallow-submodules`

```
$ du -hs bridgestan 
1.2G	bridgestan
```

**Comment by bob-carpenter** [comment]
We can just mention the current sizes doing it both ways.  I had no idea you could do that.

**Comment by bob-carpenter** [comment]
Also, how does this compare to downloading the .zip file or one of our releases?

**Comment by WardBrian** [comment]
We create the release using `tar --exclude-vcs`, which completely removes the `.git` folders (including from the submodules). By not saving any history it gets quite small.

**Comment by WardBrian** [comment]
The equivalent for a git clone would be something like

```
git clone --recurse-submodules --shallow-submodules --depth=1 https://github.com/roualdes/bridgestan.git
```
