### ISSUE TITLE
Add to Getting Started doc how to specify pre-existing Stan directory

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#138]
From our review for the Journal of Open Source Software, openjournals/joss-reviews#5236, it was recommended that we add to our documentation details on how a user could link to a pre-existing Stan directory instead of cloning Stan and Stan Math as submodules from within the BridgeStan repository.

**Comment by WardBrian** [comment]
I can tackle all three of these getting started page suggestions
