### ISSUE TITLE
Add to doc a section highlighting the functionality or lack there of across the interfaces

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#139]
From our review for the Journal of Open Source Software, openjournals/joss-reviews#5236, it was recommended that we add details discussing the similarities and differences across the interfaces.

**Comment by WardBrian** [comment]
The best place to do this is most likely on the "languages" landing page, no? https://roualdes.github.io/bridgestan/latest/languages.html

Something like
> All language interfaces expose the same core functionality from the C API [link]. Additional "quality of life" features such as the ability to download BridgeStan's source code automatically or compile models from inside the language (rather than manually calling `make`) are available on a best-effort basis. If you are missing these features in your favorite language, we would welcome a contribution!

**Comment by roualdes** [comment]
Ya, I like that.

**Comment by bob-carpenter** [comment]
I like it, too and it's exactly what I think we should write in our doc.

For the article, I'd try to stay a bit more formal in tone than "we would welcome a contribution!"   Given the space limitation, I suggest just dropping that last sentence, or at most, replacing it with some hint we might add more in the future.
