### ISSUE TITLE
Any remaining hurdles to a release?

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#19]
Continuing the conversation from #18 about when we think BridgeStan is ready for an official release and a version number.

Quoting @WardBrian.

> After this PR I personally consider this repo to be in a "releasable" state, at least for a 0.1 release if not a 1.0

Seconded.

> There are a few things remaining that I have on the list of possible features going forward, such as improved error messages (optional), and utilities in the interfaces for running compilation for you (would be very useful)

The latter would be a great feature, and improved error messages wouldn't hurt.  Both though are features, in my mind, beyond the current usable state of BridgeStan.  

Hence, I'm in favor of a 0.1 or 1.0 version number.

Any other thoughts, opinions, concerns?

**Comment by WardBrian** [comment]
I am in favor of a 0.1 release if only because I want to reserve the right to make possibly breaking changes a little longer. In particular, I think some things might become obvious when working on @bob-carpenter's library of Python sampling algorithms which could inspire changes to the interface here.

Beyond that, I also wonder what "releasing" looks like for this. Do we just want to tag a release on Github and that's that? I am not sure it makes sense to pursue releases on PyPi/CRAN/whatever Julia calls its package index

**Comment by WardBrian** [comment]
I'm not planning on figuring out the R required for `compile_model` in that interface quite yet, so to my mind #28 and improved getting started doc for both users and developers are the only things I'd like to see before tagging a release.

**Comment by WardBrian** [comment]
I would also like to say that I think at this point, a 1.0 version number seems appropriate to me. I tend to only like a pre-1.0 version if there's a concrete list of things which need to happen before 1.0, and I can't come up with one.

If we find out (for whatever reason) some part of the API does need a breaking change, I'd rather do a 2.0 in that case

**Comment by bob-carpenter** [comment]
I'm also in favor of just moving to a 1.0 release.  I also can't think of anything we intend to change or decide.

**Comment by roualdes** [comment]
Ya, let's do a 1.0 release. @WardBrian, you mind tackling this when convenient for you?

**Comment by WardBrian** [comment]
After #51 (and maybe some more doc from #43?) I'd be happy to.

**Comment by bob-carpenter** [comment]
I'm happy to finish #43 with @WardBrian's help when everything has been updated to where we want it for the release.
