### ISSUE TITLE
logo icons

### ISSUE THREAD

**Issue by bob-carpenter** [roualdes/bridgestan#199]
Same fix in two places:

1.  The icon used for web tabs shouldn't have "BridgeStan" under it.  It's way too small.

2.  On the doc pages, the icon used in upper left also shouldn't have "BridgeStan" under it because we include the name to the right.

The logo with the name under it will be good for standalone use.

**Comment by WardBrian** [comment]
I think we have the larger version without text, I’ll need to see for the favicon

**Comment by bob-carpenter** [comment]
It's easy to generate a new favicon---at least it looks like there are a lot of online tools for such.
