### ISSUE TITLE
Use new stan::math::gradient when available

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#23]
Use https://github.com/stan-dev/math/pull/2743 when it becomes available, after stan-dev/math and stan-dev/cmdstan updates.

This should reduce a copy in BridgeStan's use of `stan::math::gradient`, e.g. https://github.com/roualdes/bridgestan/blob/e89247e3dbd1b7d833a814a18f5c72f2f7f97f92/src/model_rng.cpp#L197.

**Comment by roualdes** [comment]
I think `*val` can be used directly in `stan::math::gradient` within `log_density` and similar functions, instead of creating  `double lp` and then exchanging the value as in https://github.com/roualdes/bridgestan/blob/2f730e1a201e7c5190e486c46bb22769a0e2fd01/src/model_rng.cpp#L197.

**Comment by WardBrian** [comment]
I think you’re right, that was probably missed during the change to return codes

**Comment by bob-carpenter** [comment]
OK, I'll submit a patch.

**Comment by WardBrian** [comment]
I’ve actually been running locally against CmdStan develop, which means today I needed to update some things for the new location of the JSON parser. I also took a crack at this while I was at it: https://github.com/roualdes/bridgestan/tree/stan-2-31

**Comment by roualdes** [comment]
Nice.  That this change is so seamless for BridgeStan is excellent. 

Assuming this is just a prototype, I'll save my comments until a future PR.

Do you know off the top of your head when (roughly) 2.31 is likely to be released?

**Comment by WardBrian** [comment]
The releases are ~4 months apart, so the feature freeze should start toward the end of October and the release itself should be early November.
