### ISSUE TITLE
parameter sizes not checked in log_density_gradient

### ISSUE THREAD

**Issue by bob-carpenter** [roualdes/bridgestan#239]
The `log_density_gradient` function doesn't check we get the right number of parameters in a call. 

Here's a simple reproducible example.

`bs.stan`
```stan
parameters {
  vector<lower=0, upper=1>[2] alpha;
}
```

Running it with too small, just right, and too large array of parameters:

```python
import bridgestan as bs
import numpy as np
model = bs.StanModel('bs.stan')
lp1, grad1 = model.log_density_gradient(np.array([0.3]));
lp2, grad2 = model.log_density_gradient(np.array([0.3, 0.5]));
lp3, grad3 = model.log_density_gradient(np.array([0.3, 0.5, 0.1]))
print(f"{lp1=} {lp2=} {lp3=}")
print(f"{grad1=} {grad2=} {grad3=}")
```

No errors, just this output, which looks like it ignores extra parameters and treats missing parameters as having value 0.

```python
>>> print(f"{lp1=} {lp2=} {lp3=}")
lp1=-2.795004850056945 lp2=-2.8568644572972675 lp3=-2.8568644572972675

>>> print(f"{grad1=} {grad2=} {grad3=}")
grad1=array([-0.14888503,  0.        ]) grad2=array([-0.14888503, -0.24491866]) grad3=array([-0.14888503, -0.24491866])
```

I think it'd be useful to check input size here.  This came to my attention as a bug in someone's code they were showing me that BridgeStan didn't catch.

**Comment by WardBrian** [comment]
Correct, the only sizes we currently check are on output parameters, not inputs. 

The checks are easy to add, but do lead to a performance cost that all users would have to pay

**Comment by roualdes** [comment]
We could add an input check behind a flag which allows the performance oriented to disable the check, ya?

**Comment by WardBrian** [comment]
If you're the kind of user who cares about disabling the input check, the cost of simply branching to decide whether or not that check gets run probably bugs you. I've seen people provide `foo` and `foo_unchecked` for this purpose, but of course that increases your API surface

**Comment by aseyboldt** [comment]
Is the cost of checking the input length really something that matters in any circumstances? That should be many orders of magnitude smaller than any logp evaluation anyway?

**Comment by bob-carpenter** [comment]
> Is the cost of checking the input length really something that matters

It can.  Branch point misprediction is really hard on cache.  And we're talking about Python here.  It'd be nice if we could provide branch point prediction hints like we can in C++, because we don't care about the cost on failure.

@WardBrian:  Is this an issue because our C++ class doesn't check the length of its input?  I know it reads it like a stream, so I was at least expecting an error when it was too small.

**Comment by WardBrian** [comment]
It just gets a `double*` pointer. We could also pass the length if we wanted to "check" in C++ (I use the scare quotes because of course there's no way to be sure said number is _actually_ the size of the buffer once we're down there)

What it does when it's too small will be system dependent. You might read zeros, uninitialized memory, or segfault. 


I'm trying to time the difference now. If it's in the single digit percents it is probably worth doing unconditionally

**Comment by bob-carpenter** [comment]
The density can be arbitrarily expensive, so you can drive this down to whatever fraction you want based on model size.  So it'd be interesting to test the impact on the smallest possible unidimensional normal example, I think.
