### ISSUE TITLE
Fail to run bs.StanModel in the test case

### ISSUE THREAD

**Issue by YuFuOliver** [roualdes/bridgestan#243]
Hi there, 

I am new to bridgestan, and I find that I cannot compile the test model within python. I use MacOS 14.5 with M3 chip.

I am not sure it's right but I did the following to install bridgestan:

1. I run the code `git clone --recurse-submodules https://github.com/roualdes/bridgestan.git` in the path `/Users/fu/anaconda3/envs/stan/bin`. The `stan` environment was created when I installed `cmdstan`. 
2. After `conda activate stan`, I have 
```
(base) fu@fus-MacBook-Pro ~ % conda activate stan
(stan) fu@fus-MacBook-Pro ~ % clang++ --version
clang version 16.0.6
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Users/fu/anaconda3/envs/stan/bin
(stan) fu@fus-MacBook-Pro ~ % make --version
GNU Make 4.3
Built for arm64-apple-darwin20.0.0
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

3. It was stuck when I try to run `make test_models/multi/multi_model.so`. I tried `make test_models/multi/multi_model.so -j16`. I guess it works because now I have
```
(stan) fu@fus-MacBook-Pro bridgestan % make test_models/multi/multi_model.so
make: 'test_models/multi/multi_model.so' is up to date.
```
4. I use `pip install bridgestan` within the `stan` environment.

I think I am ready to go, and thus I run the test_file at `/Users/fu/anaconda3/envs/stan/bin/bridgestan/python/example.py`. However, I got the following messages that I don't know how to deal with it:
```
/Users/fu/anaconda3/envs/stan/bin/python3 /Users/fu/anaconda3/envs/stan/bin/bridgestan/python/example.py 
Traceback (most recent call last):
  File "/Users/fu/anaconda3/envs/stan/bin/bridgestan/python/example.py", line 13, in <module>
    model = bs.StanModel(stan, data)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fu/anaconda3/envs/stan/bin/bridgestan/python/bridgestan/model.py", line 145, in __init__
    self.stanlib = ctypes.CDLL(self.lib_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fu/anaconda3/envs/stan/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/fu/anaconda3/envs/stan/bin/bridgestan/test_models/bernoulli/bernoulli_model.so, 0x0006): Symbol not found: __ZN3tbb8internal23allocate_via_handler_v3Em
  Referenced from: <C7DCE188-540B-3CAA-894B-ECBE5D729A8E> /Users/fu/anaconda3/envs/stan/bin/bridgestan/test_models/bernoulli/bernoulli_model.so
  Expected in:     <A90D8AB4-F232-3892-B6A7-4198FF713629> /Users/fu/anaconda3/lib/libtbb.12.8.dylib

Process finished with exit code 1
```

Can I have any ideas about this?

I also want to mention that outside the `stan` environment, I have
```
(base) fu@fus-MacBook-Pro ~ % clang++ --version
clang version 14.0.6
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Users/fu/anaconda3/bin
```

Thanks in advance!

**Comment by WardBrian** [comment]
Are you setting `$BRIDGESTAN` to `/Users/fu/anaconda3/envs/stan/bin`? Either in your shell environment or by caling `set_bridgestan_path`?

**Comment by YuFuOliver** [comment]
> Collaborator

Hi Brian, adding the path solves the problem. Thanks a lot for your help!

**Comment by WardBrian** [comment]
Glad to hear it!
