### ISSUE TITLE
Adding data after model construction

### ISSUE THREAD

**Issue by daslu** [roualdes/bridgestan#252]
Many thanks for creating BridgeStan.

Looking at the API, it seems like the data (the observations) can only be passed at the model construction stage (e.g., `bs_model_construct` in the C API). So, it is not possible to add data after that stage.

Possibly, there is a good reason I have not thought about yet.

Anyway, is this limitation expected to stay?

**Comment by daslu** [comment]
Of course, one may contact the data on the user side and pass it to a new `bs_model_constuct` call. 

Is this the recommended practice in a case where new observations have arrived?

**Comment by daslu** [comment]
This question was answered at the talk of @roualdes last May at the Oklahoma Data Science Workshop.
https://mediasite.ouhsc.edu/Mediasite/Channel/python/watch/93ce0ad0ede74e1e84e60ee8607d6cb91d
around 1:10:10 time.

So yes, we need to reconstruct a model for new data. :pray:

**Comment by bob-carpenter** [comment]
Yes, not only is it required in the API, it's really required conceptually for standard Monte Carlo sampling for Bayesian inference, where we are taking draws $\theta^{(m)} \sim p(\theta \mid y)$ from the posterior for fixed data $y$.

**Comment by daslu** [comment]
Makes sense. Thanks for the quick help!
