### ISSUE TITLE
Repository naming conventions

### ISSUE THREAD

**Issue by WardBrian** [roualdes/bridgestan#26]
Originally discussed in #21:
We currently have a bunch of folders named after languages (`R`, `julia`, `python`, `c-example`, `stan`) and one named `src`.

@bob-carpenter proposed renaming `src` to `cpp`. 
I'm of the opinion that `src` _is_ a special case, since all the other languages need the code contained there to function.

I do on the other hand think that `stan` sticks out, and we might want to rename it to something like `test_models` (since that's what they are). If we do that. then we have the convention that `src` is for the BridgeStan code, and any folder named after a language is for _accessing_ that code from the language it is named after

**Comment by roualdes** [comment]
I could go either way on this.  Both make sense, and I don't have a strong opinion on this other than whatever we go with should be explained in the doc.

**Comment by bob-carpenter** [comment]
Let's just go with what @WadBrian is suggesting.  I don't think it's a huge deal one way or the other.
