### ISSUE TITLE
README updates: version numbers and updates to cmdstan

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#32]
Some unrelated questions about the README file.

1. Should we list in the README Julia, Python, and R minimum version numbers?  It says Python 3, but I feel like we mean Python 3.9+.  Julia should be 1.8+.  I'd guess R should be 4+, but that's a wild guess.  Thoughts?

2. Do we want to advertise/announce/mention the C-example in the README?

3. The sentence "The second command brings in the latest version of Stan." doesn't refer to anything.  Should the code chunk above this sentence instead be

```
cd <cmdstan-dir>
make stan-update
make <bridgestan-dir>/test_models/multi/multi
```

**Comment by WardBrian** [comment]
1:
For Python, we list 3.9 in the setup.cfg file, and the `compile_model` function uses some standard library features which are 3.9+. It would be reasonable to relax this to as low as 3.7 with some minor rewrites, if we had the desire.

The `.C` interface for R is so archaic that I'm not sure what a minimum R version would be. The oldest version of R I am able to install is `R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"`, and it works for that version, so my guess is `>=3`.

2:
We can, though I'm not sure how much to say. My assumption with the C example is that anyone who knows they want to bind this from a compiled language will probably know how to do it even better than I did

3:
You're right that the prose doesn't make sense, but I think it would be better to cut the line than to add `make stan-update`. I don't think we should necessarily recommend using `develop` versions, which is what make stan-update will do.

**Comment by roualdes** [comment]
1. I'm happy with Python 3.9+, I'm just suggesting we put this info upfront instead of within each package's source code (Julia => Manifest.toml, Python => setup.cfg, src/R => DESCRIPTION).  What do you think?

2. Sounds good.  Skip.

3. That's a good point, not to recommend `develop` versions.

**Comment by WardBrian** [comment]
Yes, I think it's good to put this on the readme and in the relevant sections in https://roualdes.github.io/bridgestan/install.html
