### ISSUE TITLE
Bridgestan.jl fails to compile for julia version 1.7.2

### ISSUE THREAD

**Issue by nsiccha** [roualdes/bridgestan#35]
When I try `using BridgeStan` I get the following error:

```
[ Info: Precompiling BridgeStan [c88b6f0a-829e-4b0b-94b7-f06ab5908f5a]
ERROR: LoadError: syntax: expected assignment after "const"
Stacktrace:
  [1] top-level scope
    @ ~/.julia/packages/BridgeStan/YcHCB/src/model.jl:22
  [2] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
  [3] include(x::String)
    @ BridgeStan ~/.julia/packages/BridgeStan/YcHCB/src/BridgeStan.jl:1
  [4] top-level scope
    @ ~/.julia/packages/BridgeStan/YcHCB/src/BridgeStan.jl:24
  [5] include
    @ ./Base.jl:418 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1318
  [7] top-level scope
    @ none:1
  [8] eval
    @ ./boot.jl:373 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [10] top-level scope
    @ none:1
```

removing the const qualifiers in `model.jl` enables me to at least compile/include BridgeStan.

**Comment by nsiccha** [comment]
Ah, just saw that the prerequisites say Julia 1.8, I'm guessing it works for that.

**Comment by WardBrian** [comment]
Correct, the const members are a 1.8+ feature. You're as good as anyone to ask (@roualdes and I discussed this briefly when I introduced them) - how conservative should we be on Julia features from newer versions? I have a pretty good sense for a language like Python, but for Julia I don't know if most people update regularly or if there are holdouts on ancient versions.

**Comment by roualdes** [comment]
@nsiccha Are you satisfied with the documented Julia 1.8 requirement?  If so, can we close this issue?

**Comment by nsiccha** [comment]
@roualdes 
>  Are you satisfied with the documented Julia 1.8 requirement? If so, can we close this issue?

Sure, that was my oversight.

@WardBrian 
> how conservative should we be on Julia features from newer versions?

I have no idea. Maybe it makes sense to aim for compatibility with versions which support [AdvancedHMC](https://github.com/TuringLang/AdvancedHMC.jl)? That's what I use BridgeStan with currently.

I also don't know how easy it is to maintain different Julia versions on one machine, I'd assume not that difficult. It's obviously up to you how you handle this :)

That being said, the benefit of using the 1.8 features appears to be marginal.
