### ISSUE TITLE
Bridgestan.jl does not update modified Stan models.

### ISSUE THREAD

**Issue by nsiccha** [roualdes/bridgestan#36]
Initializing a Stan model once, then changing the Stan model in-place (i.e. editing the .stan file) and reinitializing the Stan model does not seem to update the loaded library. 

A possible but messy workaround seems to be to give each .so file an additional random string, e.g. in `compile.jl`

```julia
    rstr = randstring(6)
    dummy_file = splitext(absolute_path)[1] * "_$(rstr).stan"
    cp(absolute_path, dummy_file)
    output_file = splitext(absolute_path)[1] * "_$(rstr)_model.so"
```

**Comment by WardBrian** [comment]
I believe POSIX dlopen has this behavior where repeated calls return the same handle due to reference counting. I think you could get around it by manually calling dlclose on the library contained in the model struct, but I’m not sure this is something the bridgestan interface can address

**Comment by nsiccha** [comment]
@WardBrian I think people should know that editing the stan file will silently fail, i.e. this should be put prominently put int othe documentation.

**Comment by bob-carpenter** [comment]
> people should know that editing the stan file will silently fail, i.e. this should be put prominently put int othe documentation.

We can mention that if you change the Stan file you have to recompile.  But this is how users should expect this to work, because it's the way lm and glm work in R (if you edit the file in a fit object, it doesn't auto update), the way CmdStan(R, Py) work (you have to recompile explicitly if you change the Stan program) , and the way C++ itself works.

**Comment by nsiccha** [comment]
@bob-carpenter BridgeStan **does recompile**, IMO making the user think that the recompiled model will also be used, but it will silently use the old model if that has been compiled and loaded before. I believe this is highly unintuitive.

**Comment by nsiccha** [comment]
The following chunk of code in compile.jl fixes the issue (with high probability):
```julia
    rstr = ""
    open(absolute_path) do f
        rstr = bytes2hex(sha256(f))
    end
    dummy_file = splitext(absolute_path)[1] * "_$(rstr).stan"
    if !isfile(dummy_file)
        cp(absolute_path, dummy_file)
    end
    output_file = splitext(absolute_path)[1] * "_$(rstr)_model.so"
```

**Comment by WardBrian** [comment]
Without some good deal of bookkeeping and clean up, the above could would lead to folders filled with "mymodel_{some hash}_model.so" files.

That problem aside, depending on what changed, it is _unsafe_ to reload a model without re-starting the program. For example, if you compile a model, load it, then re-compile it but with `STAN_THREADS` enabled, trying to reload it might fail or might seg fault later on. Even calling `dlclose` first is not a full solution, as noted in the R docs for `dyn.load`:

> The function dyn.unload unlinks the DLL. Note that unloading a DLL and then re-loading a DLL of the same name may or may not work: on Solaris it uses the first version loaded. Note also that some DLLs cannot be safely unloaded at all: unloading a DLL which implements C finalizers but does not unregister them on unload causes R to crash.

It is unfortunate that this is inconsistent with cmdstan[py|r], but I think trying to patch around this behavior of `dlopen(3)` is probably not a good idea.

**Comment by nsiccha** [comment]
Then the best solution may be to warn the user.

**Comment by WardBrian** [comment]
I think a warning is reasonable

**Comment by WardBrian** [comment]
Looking into this, a warning is easy in both R and Julia. It seems like Python doesn’t give you a platform-agnostic way to list loaded DLLs, so it may not be possible to warn there

**Comment by bob-carpenter** [comment]
Sorry, @nsiccha, but I realize I'm probably seriously misunderstanding this discussion, so please ignore my previous responses.  This appears to be something related to R and Julia that's not necessarily relevant for Python, which is the only interface I've been using.

**Comment by WardBrian** [comment]
It would be relevant to Python, I just can't figure out how to also emit a warning in Python for it yet

**Comment by nsiccha** [comment]
No worries, @bob-carpenter.
