### ISSUE TITLE
A vector parameter as the first parameter in a Stan model leads to the first two parameters having a zero gradient if make/local contains `STANCFLAGS+=--O1`.

### ISSUE THREAD

**Issue by nsiccha** [roualdes/bridgestan#39]
Weirdly specific title, but that's how it appears to be.

Running the following in the folder `bridgestan/julia/mwe` outputs `(-27.5, [0.0, 0.0, -3.0, -4.0, -5.0])` for me:

```
using Pkg;
Pkg.add(url="https://github.com/roualdes/bridgestan.git", subdir="julia")
using BridgeStan
set_bridgestan_path!(pwd() * "/../..")

model_code = "
parameters {
  vector[5] fvb;
}
model {
  fvb ~ normal(0, 1);
}
"
data_string = "{}"


open("model.stan", "w") do f
    write(f, model_code)
end

open("data.json", "w") do f
    write(f, data_string)
end

model = StanModel(stan_file="model.stan", data="data.json")
println(log_density_gradient(model, collect(1.:5)))
```

**Comment by WardBrian** [comment]
Confirmed this, looking into it more

**Comment by WardBrian** [comment]
Okay, I compiled the same model with CmdStan and then ran `./grad diagnose init=p.json` where p.json was `{ "fvb": [1,2,3,4,5] }`, and this output the correct values for the gradient.

So, it seems like this is an issue only in BridgeStan somewhere

**Comment by WardBrian** [comment]
Additional findings:

Adding dummy `real` parameters before the vector changes this behavior. With the first, only one zero appears in the gradient. With the second and onward, the gradient is correct. 

Whenever the gradient is wrong, calling log_density_hessian seems to cause a segfault `in stan::math::internal::reverse_pass_callback_vari`. 

The only changes to the model's .hpp file with --O1 are the introduction of some `conditional_var_value_t`s to the calls to the deserializer's `read` - indicated SoA is being used.

**Comment by SteveBronder** [comment]
Just posting, this isn't a Stan level error as I wrote a test [here](https://gist.github.com/SteveBronder/37013c9f1a5a5c17390b08327c20a28b) to see what's going on. I think it's something in bridgestan

**Comment by roualdes** [comment]
And the plot thickens.  Thanks all for looking into this.  Much appreciated.

I had to add `set_cmdstan_path!(...)` to get this MWE to run, but then with or without `--O1`, this gives output `(-27.5, [-1.0, -2.0, -3.0, -4.0, -5.0])` for me.

I compiled the model from the command line and not, and confirmed that the .hpp file contains `return std::vector<std::string>{"stanc_version = stanc3 8fce5fb", "stancflags = --O1"};`.

macOS 12.2, Apple clang version 11.0.3, Julia 1.8.2, and I honestly don't know how to check my CmdStan version.

Has anyone narrowed this down to a specific higher level language?  Does this happen in Python or R, for those of you that can recreate this?

**Comment by bob-carpenter** [comment]
Thanks, @SteveBronder.  I couldn't quite follow the test.  Is it using a new `gradient` functional that takes array arguments?  

@roualdes or @WardBrian:  Is that what is getting called to cause the error in BridgeStan?  

Either way, I don't see how the -O1 vs -O0 could affect the soundness of the BridgeStan interface unless there are threading or memory issues somewhere introduced by the optimizations or in the interface.

**Comment by WardBrian** [comment]
For future reference if it ever comes up again, here is the code Steve and I were using to debug with `gdb`:

```c
#include "bridgestan.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
  char* data;
  if (argc > 1) {
    data = argv[1];
  } else {
    data = "";
  }
  model_rng* model = construct(data, 123, 0);
  if (!model) {
    return 1;
  }
  printf("This model's name is %s.\n", name(model));
  printf("It has %d parameters.\n", param_num(model, 0, 0));

  double params[5] = {1.0, 2.0, 3.0, 4.0, 5.0};
  double val;
  double* grad = malloc(5 * sizeof(double));
  log_density_gradient(model, 1, 1, params, &val, grad);
  printf("%f %f %f %f %f", grad[0], grad[1], grad[2], grad[3], grad[4]);
  
  return destruct(model);
}
```

The easiest way to use this is to replace `example.c` with it in the c-example folder and then link to the model provided in the original issue here.

**Comment by SteveBronder** [comment]
> Thanks, @SteveBronder. I couldn't quite follow the test. Is it using a new gradient functional that takes array arguments?

@bob-carpenter that function was just the log prob gradient call that bridgestan uses at the C level
