### ISSUE TITLE
Warning message if BRIDGESTAN is not defined

### ISSUE THREAD

**Issue by goedman** [roualdes/bridgestan#46]
Hi @roualdes 

Over the weekend Seth (@sethaxen) and I decided to include bridgestan as a Git subtree and Seth implemented this. 

It works fine (and this include Github CI workflows!). But it also always results in:
```
julia> include("/Users/rob/.julia/dev/StanSample/example/bernoulli.jl");
┌ Warning: BridgeStan path was not set, compilation will not work until you call `set_bridgestan_path!()`
└ @ StanSample.BridgeStan ~/.julia/dev/StanSample/deps/data/bridgestan/julia/src/BridgeStan.jl:40
[ Info: /Users/rob/.julia/dev/StanSample/example/tmp/bernoulli.stan updated.
4000×1 DataFrame
  Row │ theta     
      │ Float64   
──────┼───────────
    1 │ 0.239221
    2 │ 0.21372
```
as we discuss [here](https://github.com/StanJulia/StanSample.jl/pull/59#issue-1419894947). We define the BRIDGESTAN environment later on as the path to bridgestan now can vary.

I wonder if there is a better solution for this. 

A minor issue we bumped into is that cmdstan's makefile is called makefile, BridgeStan's makefile is called Makefile. On MacOS this is not a problem but on Github's CI it does not work it seems if capitalization is not correct.

Thanks for your work! 

Rob

**Comment by WardBrian** [comment]
Hi -

Can you clarify what you would like to see addressed in this issue?

**Comment by goedman** [comment]
The minor issue is simple. Given that cmdstan and bridgestan are related, my suggestion is to call both makefile-s by the same name.

The first question is much harder to answer. Maybe it is possible to delay the check (`get_bridgestan()`) until later. Currently it is called in __init__() of BridgeStan.jl which prevents StanSample.jl (or another package that would like to include BridgeStan as a subtree) to define BRIDGESTAN before the library is actually used..

**Comment by sethaxen** [comment]
`get_bridgestan` itself doesn't throw the warning. Just `__init__` does. What if `get_bridgestan` was changed to:
```julia
function get_bridgestan()
    path = get(ENV, "BRIDGESTAN", nothing)
    path === nothing && throw(ErrorException("BridgeStan path was not set, compilation will not work until you call `set_bridgestan_path!()`"))
    return path
end
```
This waits to check that `BRIDGESTAN` is set until it's needed. And since it's needed, instead of logging a warning, an error is thrown if it's not available.

**Comment by sethaxen** [comment]
> I'm also not inclined to move this project to the `Stan-dev` org, because I don't want to be governed by community voting on interfaces. I've been outvoted on all of our interfaces in the past, so I'd prefer to keep this one outside of that process.

@bob-carpenter this is a change of topic, but I was just trying to get [PosteriorDB.jl](https://github.com/sethaxen/PosteriorDB.jl) transferred to the stan-dev org so it could live with the other posteriordb interfaces. Would you advise against that?

**Comment by bob-carpenter** [comment]
> I was just trying to get [PosteriorDB.jl](https://github.com/sethaxen/PosteriorDB.jl) transferred to the stan-dev org so it could live with the other posteriordb interfaces. Would you advise against that?

Not at all.  That makes sense to roll into `posteriordb`, especially if you're happy with their interface.  That way, other people will help maintain it.  Mainly, I wanted to keep BridgeStan out of `stan-dev` until it was fully formed so I didn't have to negotiate interfaces.  We might then roll it into the project.  That's what Måns Magnusson did with `posteriordb` itself and what Paul Bürkner did with `brms` (and that still isn't on Stan-dev).

**Comment by WardBrian** [comment]
I think throwing an error in the compile methods rather than a warning at load is a good idea. The same probably goes for the Python interface.

**Comment by goedman** [comment]
Thanks a lot for fixing this so quickly!!!!
