### ISSUE TITLE
Prefix C-level functions to avoid collisions

### ISSUE THREAD

**Issue by WardBrian** [roualdes/bridgestan#53]
This would only affect users who directly include `bridgestan.h` in a project, but it is useful (and [fairly standard](https://halt.software/libraries-in-c-prefix-or-not/), I believe) to prefix C function names with a common string to avoid namespace issues that can arise in C. So, our C API would have functions like `bs_name`, while Python/Julia/R etc would still just use `name`.

I'm happy to make these changes, the question is just which prefix to use:

- `bs` short, but commonly used for another meaning
- `stan` - still short, `stan_log_density` etc all read naturally, but this isn't an official Stan project
- `bridgestan` - most accurate and unambiguous, but very long

**Comment by bob-carpenter** [comment]
I like "bs", then "stan", then "bridgestan".

**Comment by WardBrian** [comment]
I’d say that’s my personal preference as well (hence my ordering in the original post).

**Comment by roualdes** [comment]
I too agree with Brian's initial ordering.

**Comment by bob-carpenter** [comment]
> I too agree with Brian's initial ordering.

That's good news because @WardBrian has already pushed the PR and I've already reviewed it.
