### ISSUE TITLE
Can't use #include in stan files 

### ISSUE THREAD

**Issue by nsiccha** [roualdes/bridgestan#56]
As above. Trying to compile a model with include directives fails for my (from python, but I don't think it should depend on the interface).

MWE:
```
import bridgestan as bs
import os
bs.set_bridgestan_path('bridgestan')
os.system("cd bridgestan; git log --name-status HEAD^..HEAD; cd ..")

stan_functions_path = "./functions.stan"
stan_model_path = "./model.stan"
data_path = "./data.json"

with open(stan_functions_path, 'w') as fd:
    fd.write("""
functions {
    int test(){return 1;}
}
""")

with open(stan_model_path, 'w') as fd:
    fd.write("""
#include functions.stan
data {

}
parameters {
    real theta;
}
model {
    theta ~ std_normal();
}
""")

with open(data_path, 'w') as fd:
    fd.write("""{}""")


model = bs.StanModel.from_stan_file(stan_model_path, data_path)
```

Fails with output 
```
commit f62bf462175df7411893e45823926a3d04eb9263 (HEAD -> main, origin/main, origin/HEAD)
Author: Brian Ward <bward@flatironinstitute.org>
Date:   Wed Nov 30 12:54:46 2022 -0500

    Fix broken link

M       docs/install.rst

[...]

--- Translating Stan model to C++ code ---
./bin/stanc  --o=/home/niko/github/mwes/bridgestan/model.hpp /home/niko/github/mwes/bridgestan/model.stan
Makefile:49: recipe for target '/home/niko/github/mwes/bridgestan/model.hpp' failed

stderr:
Syntax error in '/home/niko/github/mwes/bridgestan/model.stan', line 2, column 0, include error:
   -------------------------------------------------
     1:  
     2:  #include functions.stan
         ^
     3:  data {
     4:  
   -------------------------------------------------

Could not find include file functions.stan in specified include paths.
make: *** [/home/niko/github/mwes/bridgestan/model.hpp] Error 1


```

**Comment by WardBrian** [comment]
Oh, when you first mentioned this on slack I thought the problem was with the C++ compilation not being able to find a necessary include. Sorry for the confusion! 

Stanc requires you specify the include paths with `—include-paths=`. So, if you use bridgestan.compile and pass that as an extra argument (`[“STANCFLAGS=--include-paths=.”]`) I believe it will work. 

CmdStanPy (and I think CmdStanR) adds the current directory as an include path by default, which is probably why this error isn’t that familiar. 

To address this in a more satisfying way we could also add this as a reasonable default, and/or we could also allow argument customization from the `from_stan_file` method rather than just the compile_model function.

**Comment by nsiccha** [comment]
> CmdStanPy (and I think CmdStanR) adds the current directory as an include path by default, which is probably why this error isn’t that familiar.

Yeah, exactly. The same model compiles with CmdStanPy without issues.

> we could also add this as a reasonable default

I think that would minimize potential friction for users :+1: 

(I for one didn't even know how to fix this doing what you described above, so I just made my python script splice in the file contents whenever things changed)

**Comment by WardBrian** [comment]
The stanc3 message could also be more informative (especially in the case where the “specified included paths” is the empty list)

**Comment by nsiccha** [comment]
Does it then actually not look anywhere at all?

**Comment by WardBrian** [comment]
Correct, the default behavior is to not look anywhere. This is important in the javascript interface, where it is actually impossible to do file lookups

**Comment by WardBrian** [comment]
Stanc improvements here: https://github.com/stan-dev/stanc3/pull/1273

Adding defaults most likely requires us making the way we accept arguments more complicated, since a user specifying their own `STANCFLAGS=` would override the default
