### ISSUE TITLE
Developer Doc and requirements?

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#6]
I just tried to build the API doc locally and found out that we need the following pip packages

* pydata-sphinx-theme
* nbsphinx

Easy enough to deal with; no complaints.

What do we think of adding some doc for developers?

**Comment by WardBrian** [comment]
We should probably add a CONTRIBUTING.md to the repo. It can document things like this, and it can also serve to answer some questions I think might come up, such as
“Can I submit a PR adding a new interface for language X” (which we will need an answer for, of course; I think it depends on what the language is)

**Comment by bob-carpenter** [comment]
Do you have a template for that @WardBrian or would you like me to take a shot at it?

**Comment by WardBrian** [comment]
Cmdstanpy has a rather short one [here](https://github.com/stan-dev/cmdstanpy/blob/develop/CONTRIBUTING.md) which I think is sort of the minimum. Usually the most useful headers for something like this are:

- Development process (describe any requirements for issues or PRs)
- Development tips/dependencies (useful commands, environment setup, etc)
- FAQ
- Code of Conduct notice/ Developer COA/license/whatever else legal things you'd like

I'd be happy for you to take a shot at it. I believe the following captures the sum total of all possible dependencies at the moment 

Install (Python): Numpy
Install (R): R6
Testing (Python): Pytest
Testing (R): testthat
Testing (Julia): Test, LinearAlgebra
Documentation: Sphinx 5.0 or greater, nbsphinx, pydata-sphinx-theme, bridgestan
