### ISSUE TITLE
Make make_args and stanc_args more prominent in Julia doc

### ISSUE THREAD

**Issue by roualdes** [roualdes/bridgestan#64]
The Julia interface, like the Python interface, allows for `make_args` and `stanc_args` to be passed from Julia (or Python) when constructing a Stan model, see [line 34 of BridgeStan.jl](https://github.com/roualdes/bridgestan/blob/33b87093a3015a15cb5780251e9457e42aef0080/julia/src/BridgeStan.jl#L34).

I think it would be helpful to have these arguments more prominently displayed in the Julia doc.  For instance, the arguments don't show up in the doc for the function `StanModel`, and only show up in the doc for `compile_model` much further down the page.

I'm raising an issue here because it's not obvious to me where in the Julia source code we should include this new documentation.

The two options, as I see it, are
 * [src/model.jl](https://github.com/roualdes/bridgestan/blob/main/julia/src/model.jl#L4-L18): right above the definition of `mutable struct StanModel`, which is where the beginning of the Julia interface doc pulls from.  However, this is not where the additional arguments, `make_args` and `stanc_args` are defined.  So it might be awkward to put documentation here for arguments to a function that are defined else where in the source code.
 * [src/BridgeStan.jl](https://github.com/roualdes/bridgestan/blob/main/julia/src/BridgeStan.jl#L34): this is where the additional arguments `make_args` and `stanc_args` are defined, but I don't think this function doc shows up in the Julia interface page.

**Comment by WardBrian** [comment]
> but I don't think this function doc shows up in the Julia interface page.

Yes, the reason there is duplication between src/model.jl and src/BridgeStan.jl is just for rendering. If I remember correctly, one place was better for Documenter.jl and one place worked better for the in-REPL help dialogues.

I think there is no harm adding more doc, provided it is in both places. The current doc does point you toward `compile_model` for more details, but just highlighting that this behavior is even possible would be useful
