### ISSUE TITLE
Gradient evaluation in Julia on multiple threads

### ISSUE THREAD

**Issue by sethaxen** [roualdes/bridgestan#67]
Thanks for the package! I'm using BridgeStan in Julia using StanSample.jl. I construct a `BridgeStan.StanModel` in order to compute `log_density_gradient`. I then use a sampler implemented in Julia to perform sampling.

Currently when I want to sample multiple chains I need to sample them serially, since if I try run the sampler within a loop marked by `Threads.@threads`, the result is a segfault at `log_density_gradient`

Is there a way to use `StanModel` in a multithreading context?

**Comment by WardBrian** [comment]
Yes, you just need to enable a compile-time flag: https://roualdes.github.io/bridgestan/getting-started.html#enabling-parallel-calls-of-stan-programs

**Comment by sethaxen** [comment]
Thanks! Seems to work!

**Comment by nsiccha** [comment]
I'm getting segfaults if I compute e.g. the logdensity of a Bridgestan model within a `Threads.@threads` for loop.

`Bridgestan.model_info` output:

```
BridgeStan version: 2.6.1
Stan version: 2.36.0
Stan C++ Defines:
        STAN_THREADS=true
        STAN_MPI=false
        STAN_OPENCL=false
        STAN_NO_RANGE_CHECKS=false
        STAN_CPP_OPTIMS=false
        BRIDGESTAN_AD_HESSIAN=false
Stan Compiler Details:
        stanc_version = stanc3 v2.36.0
        stancflags = 

```

**Comment by nsiccha** [comment]
The behaviour actually super strange:
* If I compile with `make_args=["STAN_THREADS=true"]`, I get a segfault if I evaluate the logdensity inside a @threads loop, even with a single thread.
* If I compile with `make_args=["STAN_THREADS="]`, I get a segfault if I evaluate the logdensity inside a @threads loop, **but only if multiple threads try to use the same model file**.

For me, this currently means that parallelism only works if `STAN_THREADS=false`, and each BridgeStan model loads its own .so file.

**Comment by WardBrian** [comment]
It’s hard to say without seeing more of your code, one known issue is if you are mixing models without STAN_THREADS and models with STAN_THREADS in the same process, this usually leads to segfaults

**Comment by nsiccha** [comment]
I suspect it's actually only the logdensity function which causes the segfault. For me, the below crashes:

```julia
using BridgeStan

const BS = BridgeStan

bernoulli_stan = joinpath(BS.get_bridgestan_path(), "test_models/bernoulli/bernoulli.stan")
bernoulli_data = joinpath(BS.get_bridgestan_path(), "test_models/bernoulli/bernoulli.data.json")
make_args = ["STAN_THREADS=true"]

mktempdir() do path
    new_path = joinpath(path,  "model.stan")
    cp(bernoulli_stan, new_path)
    smb = BS.StanModel(new_path, bernoulli_data; make_args);

    println(BS.model_info(smb))
    println("This model's name is $(BS.name(smb)).")
    println("It has $(BS.param_num(smb)) parameters.")

    Threads.@threads for i in 1:1
        rv = 0.
        for j in 1:1000
            # lp, grad = BS.log_density_gradient(smb, rand(BS.param_unc_num(smb)), jacobian = false)
            # The below crashes, the above doesn't.
            lp = BS.log_density(smb, randn(BS.param_unc_num(smb)))
            rv += lp 
        end
    end
    println("Did I crash?")
end
```

**Comment by WardBrian** [comment]
Oh, I have a theory then. Two quick questions:

If you call log_density_gradient first (on each thread), do subsequent calls to log density succeed?

Separately, if you pass propto=false, does it succeed?

If the answer to either of these is “yes” then I think this is an easy fix

**Comment by nsiccha** [comment]
Ah, wait, why did I contain this jacobian=false thing, already before? 🤔

**Comment by nsiccha** [comment]
Well, just so you know, removing `jacobian=false` doesn't change the behaviour.

**Comment by WardBrian** [comment]
The jacobian argument shouldn’t matter (under my hypothesis, at least).

Propto=true is weird for log_density, because it actually requires us to use autodiff types, but just never call grad. This has caused some bugs before, and I think this time it’s because we never set up the autodiff stack to be thread safe in log_density. 

Propto=false will avoid this, and any call to the other log_density functions will create a thread instance of the AD chain, so that’s why I was asking. It seems like it should just be an easy fix of adding a static thread local stack instantiation to the log_density function

**Comment by nsiccha** [comment]
Sounds like it makes sense, from my understanding of how `propto` and the AD types interact!
