### ISSUE TITLE
Registering BridgeStan.jl?

### ISSUE THREAD

**Issue by sethaxen** [roualdes/bridgestan#69]
Are you interested in adding BridgeStan.jl to the general Julia registry? This would make it easier for downstream packages like StanSample.jl to make sure they maintain compatibility with BridgeStan, since they could add BridgeStan as a dependency with version bounds. e.g. recently BridgeStan.jl dropped support for Julia versions older than Julia v1.8, which caused StanSample to break when BridgeStan was available and included.

I think the main challenge here is making sure that BridgeStan.jl has access to the rest of the bridgestan repo. Registering the package directly from the `BridgeStan` subdirectory wouldn't package its parent directory with it.

But it should be fairly straightforward to support this by making the tarball associated with the most recent bridgestan GitHub release an [Artifact](https://pkgdocs.julialang.org/v1/artifacts/). Upon BridgeStan.jl installation, the tarball is automatically downloaded and extracted and the path is made available to BridgeStan.jl. The tarball also contains all git submodules. This is, for example, how [PosteriorDB.jl](https://github.com/sethaxen/PosteriorDB.jl) interacts with posteriordb.

When a major change is made to bridgestan, the process for updating BridgeStan.jl would be 1) make a GitHub release (generates the tarball) 2) update an `Artifacts.toml` file in BridgeStan.jl. 3) register a new BridgeStan.jl. Step 2 can be [automated](https://github.com/sethaxen/PosteriorDB.jl/blob/main/.github/workflows/UpdateArtifacts.yml).

If you're interested in this, I could open a PR to set up the artifacts.

**Comment by WardBrian** [comment]
We decided fairly early on that this wouldn't be a priority for us, but it also isn't something I am personally opposed to. I believe we would also be able to do something similar for Python, but I don't think we have any intention of ever trying to wrangle this onto CRAN, so we'd have to be okay with very different installation instructions depending on language

**Comment by roualdes** [comment]
I agree with Brian on all accounts.  I also think it would be a little awkward to have registered packages for Julia and Python, but not for R.  Though I could get over this.  

@bob-carpenter, what do you think about having registered packages for Julia (and possibly Python), but not for R?  Are you against having different installs for different interfaces?

**Comment by bob-carpenter** [comment]
> what do you think about having registered packages for Julia (and possibly Python), but not for R? 

I have no experience with Julia.  I'm OK registering Python.  My advice is to avoid CRAN at all cost, but if someone else wants to deal with that pain, I won't stop you.

> Are you against having different installs for different interfaces?

I don't see how they could be the same, so I'm not against them being different.

**Comment by roualdes** [comment]
Ok, let's try.  Seth, you want to give this a go?  My only request is no added dependencies.

**Comment by WardBrian** [comment]
I’d also love if as much as possible it was doable in a push-button way from a GitHub action. If/when I get around to packing in python that will be my target

**Comment by sethaxen** [comment]
> Ok, let's try. Seth, you want to give this a go? My only request is no added dependencies.

Sure! I've opened a PR at #70. No problem, no additional dependencies needed.

> I’d also love if as much as possible it was doable in a push-button way from a GitHub action.

Agreed! It's pretty easy for registration to be push-button (already in #70). Keeping the artifact up-to-date can also be done this way (as in PosteriorDB), but it requires some more assumptions about what future releases of bridgestan will look like.

**Comment by WardBrian** [comment]
@sethaxen you can now monitor https://github.com/JuliaRegistries/General/pull/76783

Thanks for the help with this!

**Comment by sethaxen** [comment]
Excellent, thanks!
