### ISSUE TITLE
BridgeStan folder '/usr/local/lib/python3.9' does not contain file 'Makefile'

### ISSUE THREAD

**Issue by yixiang-xu** [roualdes/bridgestan#71]
Hi, follow up on #68 , I successfully installed the bridge_stan on Google Colab. And set the Python version on Colab to 3.9.16 and used the following code to test indeed the version is correct. 
```
import sys
print(sys.version)
```
> `3.9.16 (main, Dec  7 2022, 01:11:51) \n [GCC 9.4.0]`

However, I still cannot run the example because I keep getting this error msg now:
```
ValueError: BridgeStan folder '/usr/local/lib/python3.9' does not contain file 'Makefile', please ensure it is built properly!
If you need to set a different location, call 'set_bridgestan_path()'
```

Below is the example python code: 
```
import bridgestan as bs
import numpy as np
stan = "/content/bridgestan/test_models/bernoulli/bernoulli.stan"
data = "/content/bridgestan/test_models/bernoulli/bernoulli.data.json"
model = bs.StanModel.from_stan_file(stan, data)
```

I have also tried some recommendation in #68 , such as changing bridgestan to bridgestan_repo: 
```
!pip install /content/bridgestan_repo/python
```

Here is the google [colab](https://colab.research.google.com/drive/1m33yPt3Vl5oOCiTt7mSpz_l83DXTq-xW?usp=sharing) file I'm running

**Comment by WardBrian** [comment]
Based on the error `If you need to set a different location, call 'set_bridgestan_path()'`, I think the next thing to try is `bs.set_bridgestan_path('/content/bridgestan/`) before calling `StanModel.from_stan_file`

**Comment by yixiang-xu** [comment]
Thanks! It works now!
