### ISSUE TITLE
Could "pip install bridgestan" install stan?

### ISSUE THREAD

**Issue by justindomke** [roualdes/bridgestan#79]
It would be nice to be able to create downstream "user-facing" packages in python that use bridgestan, but allow people to install those packages via a simple `pip install mypackage` (and have pip dependency management install bridgestan as needed). The challenge with that is that as currently implemented, there are some manual steps to install bridgestan. Would it be possible to have bridgestan try to install stan itself (like pystan does) to avoid those manual steps? (Surely this would require some kind of compiler to exist on the user's system?) Possibly this could be done as some kind of option like `pip install bridgestan[batteriesincluded]`.

**Comment by WardBrian** [comment]
This was done for Julia in #70. We could do something similar in Python, but there is not a unified location for such things like Julia has.

In CmdStanPy we use `~/.cmdstan/cmdstan-VERSION/` as the folder. We could do something similar here if we wanted to.
