### ISSUE TITLE
Consider adding CITATION file or citation instructions in README

### ISSUE THREAD

**Issue by jtassarotti** [roualdes/bridgestan#85]
Thank you for this very useful project. I am using BridgeStan in a forthcoming paper and would like to properly cite it. Is there a preferred style or reference to cite? If there is, GitHub supports special CITATION files (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) that would make it easy to document the preferred citation style.

**Comment by WardBrian** [comment]
We have a JOSS submission under review now. I’m not sure what our best option is unless/until that gets accepted for citations, thoughts @roualdes?

**Comment by bob-carpenter** [comment]
Thanks, @jtassarotti.  I'll add a `CITATION.cff` file to the repo.  As @WardBrian notes, the only thing we have to cite now is the repository itself.  And we haven't set it up for DOIs yet.  I'm always reluctant to start adding an official author list to an open source project, but new authors can just pile in to the citation file.

**Comment by bob-carpenter** [comment]
I created a PR to add a `CITATION.cff`.  

We could also plug in Zenodo to generate DOIs.  I didn't do it because I was too lazy to look up the procedure.
