### ISSUE TITLE
Thread safety of `param_constrain`

### ISSUE THREAD

**Issue by WardBrian** [roualdes/bridgestan#92]
Forking this issue off some discussion in #90 and something @justindomke asked me about when using JAX:

Because of the presence of an RNG in the `bs_model` class, it is difficult to treat it as fully thread safe. 
This is only there because it is required for `write_array` in the Stan model class, and we furthermore know it is only really _used_ by said function if the generated quantities block calls `_rng` functions in the Stan code.

Thread-safe options for this which would be relatively small changes:

1. Take in an `int seed` to each call to param_constrain, which initializes a `boost:ecuyer1988` RNG, uses it once, and throws it away. This can get kind of sketchy, see recent changes in Stan: https://github.com/stan-dev/stan/pull/3168. BUT, this plays nicely with the JAX idea of `vmap`/`pmap`, etc.
2. Expose the ability to create an RNG object to the interface, and require that `param_constrain` is passed one of these if `include_gq == true`. Thread safety then comes from each thread having its own unique RNG object they pass in.

I think option 1 is the easiest to use, since it doesn't require you juggling this other object, but obviously has the potential to be less performant and requires some outside source of entropy to produce fresh seeds.

**Comment by WardBrian** [comment]
> In fact, the argument for the RNG could accept a seed and just construct one, but then that's more branching we don't necessarily want.

You bring up a good point here which is that these are not necessarily contradictory solutions. You could have two different functions, one which accepts a pre-made RNG, and one which accepts a seed, and they both call the same underlying code with the later just creating the RNG, using it once, and throwing it away. 

Unless we're opposed to having multiple ways of doing the same thing, having both seems like it would be good to cater to different kinds of users

**Comment by WardBrian** [comment]
Working through an implementation now, and I'm realizing there isn't really any reason for the Python bindings to not keep both a model and an RNG around, since the default assumption in Python is that everything is essentially in serial. 

So we could keep backwards compatibility at the Python level by just storing two pointers, one to the model and one to an RNG we create at initialization time. This will look pretty transparent to the Python user, just now `param_constrain` will have extra arguments they can use if they were in a case where they did want to do some kind of parallel map over different seeds a-la JAX. 
There's in principle no reason we couldn't do this in R as well. Julia this might not be the best idea, since threading is much more likely to occur. 

I'm torn on this because it seems like something that would be very nice for users who aren't deeply concerned with threading and just want to use Bridgestan as you currently can, but the explanation of what is actually happening seems so much more difficult in that setup as opposed to the one where the source of randomness is always required.

**Comment by bob-carpenter** [comment]
> but the explanation of what is actually happening seems so much more difficult

Is that required for the user-facing Python doc?  If not, I'm OK with some complication under the hood if it allows simpler API calls in typical use cases.

**Comment by WardBrian** [comment]
I think it would be required to explain in order to communicate what the `seed` and `rng` arguments are/why you might use them
